- name: backend deployment
  k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: backend
        namespace: default
        labels:
          app: backend
      spec:
        replicas: 3
        selector:
          matchLabels:
            app: backend
        template:
          metadata:
            labels:
              app: backend
          spec:
            containers:
            - name: backend
              image: backend-ccc39
              imagePullPolicy: Never
              ports:
              - containerPort: 8081
- name: check if deployment is ready
  k8s_info:
    kind: Deployment
    label_selectors:
      - app = backend
  register: output_info
  until: output_info.resources | json_query('[*].status.conditions[?reason==`NewReplicaSetAvailable`][].status') | select ('match','True') | list | length == 1
  delay: 10
  retries: 5

- name: printing out the message
  debug:
    msg: '{{output_info}}'

- name: backend service
  k8s:
    state: present
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: backend-service
        namespace: default
        labels:
          app: backend
      spec:
        type: ClusterIP           # NodePort service
        clusterIP: None
        ports:
        - port: 8081
          targetPort: 8081        # external port
          protocol: TCP
        selector:
          app: backend     # label selector
