- name: Install pip
  become: yes
  ansible.builtin.apt:
    name: ['python3-dev', 'python3-setuptools', 'python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: updating pip
  become: true
  ansible.builtin.pip:
    name: ['pip']
    state: latest

- name: install python docker client on the workers
  become: true
  ansible.builtin.pip:
    name: ['docker']
    state: latest


- name: "build docker container image"
  become: true
  docker_image:
    name: "{{item}}-ccc39"
    build:
      path: "./ccc39-assignment/{{item}}"
    source: build
    state: present
  loop: "{{component}}"
