- name: install python docker client on the workers
  become: true
  ansible.builtin.pip:
    name: ['docker']
    state: latest


- name: "build docker container image"
  become: true
  docker_image:
    name: "{{item}}-ccc39"
    build:
      path: "./ccc39-assignment/{{item}}"
    source: build
    state: present
  loop: "{{component}}"
